model:
  name: PhaseNet
  epochs: 10
  path: "outputs/2025-06-13/01-06-21/models/epoch_15/model_weights.pth"
  
metrics:
  mph: 0.6
  mpd: 10

defaults:
  - data: hakone
  - _self_

hydra:
  job:
    chdir: True
